[server]
headless = true
runOnSave = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1B5E20"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#212121"
font = "sans serif"

[client]
showSidebarNavigation = false
